### ISSUE TITLE
Build failed in the environments of Windows SDK version 10.0.22621.0 and Windows 10.0.19044.

### ISSUE THREAD

**Issue by tingtho** [jvstech/llvm-toolchain#12]
+ build command `cmake -P build-llvm-toolchain.cmake`
   + The error log indicates that the HOST_ARCH variable has not been set. It's strange because isn't the HOST_ARCH variable already set by default in build-llvm-toolchain.cmake? Perhaps there was an issue with how the variable was passed, or do we need additional commands to build it?
   + https://github.com/jvstech/llvm-toolchain/blob/main/build-llvm-toolchain.cmake#L175
+ Error Logs 
```
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- Build target: Windows
CMake Error at E:/LLVM/llvm-toolchain/cmake/modules/Validate.cmake:9 (message):
  HOST_ARCH must be defined.
Call Stack (most recent call first):
  llvm/CMakeLists.txt:30 (validate)
-- Configuring incomplete, errors occurred!
```

**Comment by jvstech** [comment]
It looks like you're running this _on_ Windows. My apologies for the confusion; I didn't indicate anywhere in the readme that this has only been written for and tested on Linux. You can cross-compile an LLVM toolchain _for_ Windows _from_ Linux, but I haven't written anything specific to support native builds on Windows.

The reason it's failing at this particular point is because [`CMAKE_SYSTEM_NAME` is blank](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html):

> Note that `CMAKE_SYSTEM_NAME` is not set to anything by default when running in script mode, since it's not building anything.

I'm not against getting this to work on Windows, but I originally wrote it as a means to have a consistent "minimal" toolchain (Clang, LLD, and Compiler-RT) built on Linux.

If nothing else, I absolutely have to update `README.md` to indicate this isn't designed to be run on Windows, and it would be best to add a `CMAKE_HOST_SYSTEM_NAME` check so a proper error/warning message can be displayed.

**Comment by tingtho** [comment]
> It looks like you're running this _on_ Windows. My apologies for the confusion; I didn't indicate anywhere in the readme that this has only been written for and tested on Linux. You can cross-compile an LLVM toolchain _for_ Windows _from_ Linux, but I haven't written anything specific to support native builds on Windows.
> 
> The reason it's failing at this particular point is because [`CMAKE_SYSTEM_NAME` is blank](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html):
> 
> > Note that `CMAKE_SYSTEM_NAME` is not set to anything by default when running in script mode, since it's not building anything.
> 
> I'm not against getting this to work on Windows, but I originally wrote it as a means to have a consistent "minimal" toolchain (Clang, LLD, and Compiler-RT) built on Linux.
> 
> If nothing else, I absolutely have to update `README.md` to indicate this isn't designed to be run on Windows, and it would be best to add a `CMAKE_HOST_SYSTEM_NAME` check so a proper error/warning message can be displayed.

Thank you for your investigation and for developing such a helpful script for compilation. I will try to compile it on Linux.
